---
language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
script: grunt test:ci
env:
  global:
  - secure: ! 'CNgN1/u5oWg7gUwkC5V6rty8iRyWmG9vrC0CFSjLP7A9d+TWvHeGZFG4lRE3

      dT2pyn+tJG+dBFPB8Xp/OpD9CY/OD7O7J+jy7julKs0er1CXxi68MHcpvleT

      H4//vtpQWpieSIyTEggvNzbjpS4YgZD7Zvm0HhST2yfVprEs+L8='
  - secure: ! 'h8e7lZzxSnKyjndsp4r370/vOSmOjQyvaH05Ga+igzJFVTYpxFLngLTJ9h32

      YxSCn0gJ4kg2y+1JY0bkcX6h3TAeniYevBtqQ3Yn6MaBnkhGwWoDM/oKXRUz

      nLWdI1OnLSy03zsAklCr7YbhdWu/k6MVLhExE757w7knIpLMtHg='
